### ISSUE TITLE
Loads of warnings about method redefinitions

### ISSUE THREAD

**Issue by giordano** [JuliaSparse/SparseArrays.jl#481] opened 2024-01-02 21:07 UTC
[Example](https://github.com/JuliaSparse/SparseArrays.jl/actions/runs/7320268569/job/19939148646#step:7:109)
```
Unbound type parameters detected:
[1] _absspvec_vcat(X::AbstractSparseVector{Tv, Ti}...) where {Tv, Ti} @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1192
[2] _absspvec_hcat(X::AbstractSparseVector{Tv, Ti}...) where {Tv, Ti} @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1154
[3] _getmode(::typeof(*), ::Type, ::Type{Union{Missing, T}}) where T @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1593
[4] _getmode(::typeof(*), ::Type{Union{Missing, T}}, ::Type{Union{Missing, S}}) where {T, S} @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1594
[5] _getmode(::typeof(*), ::Type{Union{Missing, T}}, ::Type) where T @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1592
Possible type-piracy detected:
[1] _cat(dims, X1::Union{Number, AbstractVecOrMat{<:Number}}, X::Union{Number, AbstractVecOrMat{<:Number}}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1260
[2] hcat(n1::Number, ns::Number...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1302
[3] hcat(n1::N, ns::N...) where N<:Number @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1304
[4] hcat(X::Union{Vector, AbstractSparseVector}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1241
[5] hcat(X1::Union{Number, AbstractVecOrMat{<:Number}}, X::Union{Number, AbstractVecOrMat{<:Number}}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1267
[6] hvcat(rows::Tuple{Vararg{Int32}}, n1::Number, ns::Number...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1306
[7] hvcat(rows::Tuple{Vararg{Int32}}, n1::N, ns::N...) where N<:Number @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1307
[8] hvcat(rows::Tuple{Vararg{Int32}}, X1::Union{Number, AbstractVecOrMat{<:Number}}, X::Union{Number, AbstractVecOrMat{<:Number}}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1279
[9] promote_to_array_type(A::Tuple{Vararg{Union{Number, UniformScaling, AbstractVecOrMat{<:Number}}}}) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1311
[10] vcat(n1::Number, ns::Number...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1303
[11] vcat(n1::N, ns::N...) where N<:Number @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1305
[12] vcat(X::Union{Vector, AbstractSparseVector}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1247
[13] vcat(X1::Union{Number, AbstractVecOrMat{<:Number}}, X::Union{Number, AbstractVecOrMat{<:Number}}...) @ SparseArrays ~/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:1273
[...]
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Tuple{Integer, Integer}) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2717 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{T, Ti} where Ti<:Integer, Integer, Integer) where {T} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2719 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Any, Integer, Integer) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:3168 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Tv, Ti) where {Tv, Ti<:Integer} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:429 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Any, Integer) where {Tv, Ti<:Integer} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:447 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseArray{Tv, Ti, 1} where Ti where Tv, Integer) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:986 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Tuple{Integer, Integer}) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2717.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{T, Ti} where Ti<:Integer, Integer, Integer) where {T} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2719.
WARNING: Method definition setindex!(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Any, Integer, Integer) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:3168.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Tv, Ti) where {Tv, Ti<:Integer} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:429.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Any, Integer) where {Tv, Ti<:Integer} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:447.
WARNING: Method definition getindex(SparseArrays.AbstractSparseArray{Tv, Ti, 1} where Ti where Tv, Integer) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:986.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Tuple{Integer, Integer}) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2717 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{T, Ti} where Ti<:Integer, Integer, Integer) where {T} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2719 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Any, Integer, Integer) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:3168 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Tv, Ti) where {Tv, Ti<:Integer} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:429 overwritten.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Any, Integer) where {Tv, Ti<:Integer} in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:447 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseArray{Tv, Ti, 1} where Ti where Tv, Integer) in module SparseArrays at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:986 overwritten.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Tuple{Integer, Integer}) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2717.
WARNING: Method definition getindex(SparseArrays.AbstractSparseMatrixCSC{T, Ti} where Ti<:Integer, Integer, Integer) where {T} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:2719.
WARNING: Method definition setindex!(SparseArrays.AbstractSparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Any, Integer, Integer) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsematrix.jl:3168.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Tv, Ti) where {Tv, Ti<:Integer} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:429.
WARNING: Method definition setindex!(SparseArrays.AbstractCompressedVector{Tv, Ti}, Any, Integer) where {Tv, Ti<:Integer} in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:447.
WARNING: Method definition getindex(SparseArrays.AbstractSparseArray{Tv, Ti, 1} where Ti where Tv, Integer) in module SparseArrays overwritten at /home/runner/work/SparseArrays.jl/SparseArrays.jl/src/sparsevector.jl:986.
[...]
WARNING: Method definition getproperty(SparseArrays.SparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module HigherOrderFnsTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:4 overwritten in module SparseIssuesTests on the same line (check for duplicate calls to `include`).
WARNING: Method definition getproperty(SparseArrays.SparseVector{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module HigherOrderFnsTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:5 overwritten in module SparseIssuesTests on the same line (check for duplicate calls to `include`).
[...]
WARNING: Method definition getproperty(SparseArrays.SparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseIssuesTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:4 overwritten in module SparseLinalgTests on the same line (check for duplicate calls to `include`).
WARNING: Method definition getproperty(SparseArrays.SparseVector{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseIssuesTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:5 overwritten in module SparseLinalgTests on the same line (check for duplicate calls to `include`).
[...]
WARNING: Method definition getproperty(SparseArrays.SparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseLinalgTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:4 overwritten in module SparseMatrixConstructorIndexingTests on the same line (check for duplicate calls to `include`).
WARNING: Method definition getproperty(SparseArrays.SparseVector{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseLinalgTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:5 overwritten in module SparseMatrixConstructorIndexingTests on the same line (check for duplicate calls to `include`).
[...]
WARNING: Method definition getproperty(SparseArrays.SparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseMatrixConstructorIndexingTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:4 overwritten in module SparseTests on the same line (check for duplicate calls to `include`).
WARNING: Method definition getproperty(SparseArrays.SparseVector{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseMatrixConstructorIndexingTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:5 overwritten in module SparseTests on the same line (check for duplicate calls to `include`).
[...]
WARNING: Method definition getproperty(SparseArrays.SparseMatrixCSC{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:4 overwritten in module SparseVectorTests on the same line (check for duplicate calls to `include`).
WARNING: Method definition getproperty(SparseArrays.SparseVector{Tv, Ti} where Ti<:Integer where Tv, Symbol) in module SparseTests at /home/runner/work/SparseArrays.jl/SparseArrays.jl/test/forbidproperties.jl:5 overwritten in module SparseVectorTests on the same line (check for duplicate calls to `include`).
```

**Comment by ViralBShah** [comment] 2024-01-03 05:06
cc @vtjnash

**Comment by vtjnash** [comment] 2024-01-03 18:48
Duplicate of https://github.com/JuliaSparse/SparseArrays.jl/issues/409 (by design?)

**Closed by vtjnash** 2024-01-03 18:48 UTC
